# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# Linting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude_types: [jupyter]
  - id: check-toml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
  - id: black-jupyter
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
# Python static analysis
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.199'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
      args: ["--force-exclude"]
# Shell static analysis
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.8.0
  hooks:
  - id: shellcheck
  # precommit invokes shellcheck once per file. shellcheck complains if file
  # includes another file not given on the command line. Ignore this, since
  # they'll just get checked in a separate shellcheck invocation.
    args: ["-e", "SC1091"]
# Misc
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    args: ["--skip=*.pyc,tests/testdata/*,*.ipynb,*.csv","--ignore-words-list=codebook"]
# Hooks that run in local environment (not isolated venv) as they need
# same dependencies as our package.
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
