model_args:
  model_name_or_path: EleutherAI/pythia-70m-deduped
  cache_dir: /data/.cache/huggingface/
data_args:
  dataset_name: wikitext
  dataset_config_name: wikitext-103-v1
  streaming: False
training_args:
  run_name: train_gpt2_on_wiki
  output_dir: output_main
  overwrite_output_dir: True
  do_train: True
  do_eval: True
  per_device_train_batch_size: 24
  per_device_eval_batch_size: 8
  warmup_ratio: 0.0
  learning_rate: 5e-4
  max_steps: 15000
  logging_first_step: True
  logging_steps: 50
  evaluation_strategy: steps
  eval_steps: 50
  save_steps: 10000
  ddp_find_unused_parameters: False

  train_model_params: True
  model_lr_factor: 0.1
  codebook_reg_p: null
  codebook_weight_decay: 0.01

codebook_args:
  codebook_type: vanilla
  codebook_size: 10000
  num_codebooks: 1
  layers_to_snap: all
  similarity_metric: inner_product
  codebook_at: attention
  loss: aeloss
  k_codebook: 100
  kmeans_init: False
  kmeans_path: /data/.cache/huggingface/kmeans_embeddings.pt
  kmeans_init_examples: 1000
  kmeans_kwargs:
    n_init: auto
    batch_size: 24576

k_scheduler_kwargs:
  k_max: 10000
  decay_steps: 5000

pretrained_path: null
get_baseline: False
tag_keys: []
tags: []
project: gpt2-codebook
