model_args:
  model_name_or_path: EleutherAI/pythia-70m-deduped
  cache_dir: /data/.cache/huggingface/
data_args:
  dataset_name: wikitext
  dataset_config_name: wikitext-103-v1
  streaming: False
training_args:
  run_name: train_gpt2_on_wiki
  output_dir: output_main
  overwrite_output_dir: True
  do_train: True
  do_eval: True
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  warmup_ratio: 0.1
  learning_rate: 5e-5
  max_steps: 20000
  logging_first_step: True
  logging_steps: 100
  evaluation_strategy: steps
  eval_steps: 100
  save_steps: 10000
  ddp_find_unused_parameters: False

  train_model_params: True
  model_lr_factor: 0.1
  loss: base
  codebook_reg_p: null
  codebook_weight_decay: 0.01

pretrained_path: null
get_baseline: False
codebook_size: 1000
layers_to_snap: all
similarity_metric: euclidean
codebook_at: attention
num_compositional_codebooks: 1
k_codebook: 3
tag_keys: []
tags: []
project: gpt2-codebook
