model_args:
  model_name_or_path: taufeeque/tiny-gpt2
data_args:
  dataset_name: wikitext
  dataset_config_name: wikitext-2-raw-v1
  max_train_samples: 2
  max_eval_samples: 2
  streaming: False
training_args:
  run_name: test
  output_dir: output
  overwrite_output_dir: True
  do_train: True
  do_eval: True
  max_steps: 2
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  report_to: none

get_baseline: False
codebook_size: 100
layers_to_snap: [-1, -5]
similarity_metric: euclidean
codebook_at: attention_and_mlp
num_compositional_codebooks: 2
train_model_params: False
model_lr_factor: 0.1
vqvae_loss: True
tag_keys: []
project: gpt2-codebook
