model_args:
  model_name_or_path: gpt2
data_args:
  dataset_name: the_pile
  max_train_samples: 2
  max_eval_samples: 2
  streaming: True
training_args:
  run_name: test
  output_dir: output
  overwrite_output_dir: True
  do_train: True
  do_eval: True
  max_steps: 4
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  report_to: none

get_baseline: False
codebook_size: 100
layers_to_snap: [-1, -5]
similarity_metric: euclidean
train_model_params: True
tag_keys: []
project: gpt2-codebook
